name: daily_affirmation
description: "Start your day with positivity. Get beautiful affirmations and inspiring images, automatically translated for you."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.1
  firebase_core: ^2.24.2 
  cached_network_image: ^3.3.1
  google_mobile_ads: 6.0.0
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  share_plus: ^11.0.0
  share_plus_platform_interface: ^6.0.0 
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4 # Correctly placed here
  flutter_driver: # Correctly placed here
    sdk: flutter

flutter_launcher_icons: # Correctly placed as a top-level key
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/icon.png"
  min_sdk_android: 23

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env